# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'perfectDay0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON', '~> 4.0'
pod 'TextFieldEffects'
pod 'Hero'
pod 'Alamofire', '~> 5.0.0-rc.3'
  # Pods for perfectDay0

end
