#Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NetworkTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 5.0.0-rc.3'
pod 'CryptoSwift', '~> 1.0'
  # Pods for NetworkTest

end
